name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      BATON_MIRO_ACCESS_TOKEN: ${{ secrets.MIRO_ACCESS_TOKEN }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run go tests
        run: (set -o pipefail && go test -v -covermode=atomic -json -race ./... | tee test.json)
      - name: Annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json

  integration-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_MIRO_ACCESS_TOKEN: ${{ secrets.MIRO_ACCESS_TOKEN }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-miro
        run: go build -o baton-miro ./cmd/baton-miro
      - name: Validate capabilities
        run: |
          ./baton-miro \
            --miro-access-token "$BATON_MIRO_ACCESS_TOKEN" \
          capabilities
      - name: Run basic sync test
        run: |
          ./baton-miro \
            --miro-access-token "$BATON_MIRO_ACCESS_TOKEN" \
            --log-level debug \
            --file sync.c1z

          if [ ! -f "sync.c1z" ]; then
            echo "Error: File sync.c1z was not generated."
            exit 1
          fi
      - name: List Baton Commands
        run: ./baton-miro --help
