name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test-teams:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_MIRO_ACCESS_TOKEN: ${{ secrets.MIRO_ACCESS_TOKEN }}
      BATON_MIRO_SCIM_ACCESS_TOKEN: ${{ secrets.MIRO_SCIM_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-miro
        run: go build ./cmd/baton-miro
      - name: Get baton
        uses: ConductorOne/github-workflows/actions/get-baton@v3
      - name: Grant/revoke team test
        uses: ConductorOne/github-workflows/actions/sync-test@v3
        with:
          connector: ./baton-miro
          baton-entitlement: "${{ vars.TEST_TEAM_ENTITLEMENT }}"
          baton-principal: "${{ vars.TEST_TEAM_PRINCIPAL }}"
          baton-principal-type: "${{ vars.TEST_TEAM_PRINCIPAL_TYPE }}"
  test-roles:
    needs: [test-teams]
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_MIRO_ACCESS_TOKEN: ${{ secrets.MIRO_ACCESS_TOKEN }}
      BATON_MIRO_SCIM_ACCESS_TOKEN: ${{ secrets.MIRO_SCIM_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-miro
        run: go build ./cmd/baton-miro
      - name: Get baton
        uses: ConductorOne/github-workflows/actions/get-baton@v3
      - name: Grant/revoke role test
        uses: ConductorOne/github-workflows/actions/sync-test@v3
        with:
          connector: ./baton-miro
          baton-entitlement: "${{ vars.TEST_ROLE_ENTITLEMENT }}"
          baton-principal: "${{ vars.TEST_ROLE_PRINCIPAL }}"
          baton-principal-type: "${{ vars.TEST_ROLE_PRINCIPAL_TYPE }}"
